// <auto-generated/>
#nullable disable
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Dbus.Contracts;

namespace GeneratorHarness.Generated;

[DbusInterface("org.example.Corpus")]
[DbusProperties(typeof(CorpusProperties))]
public interface ICorpus : IDbusObject
{
    [DbusMethod("Ping", "", "", false)]
    Task PingAsync();
    Task<T> GetAsync<T>(string prop);
    Task<CorpusProperties> GetAllAsync();
    Task SetAsync(string prop, object val);
    Task<IDisposable> WatchPropertiesAsync(Action<DbusPropertyChanges> handler);
}

[DbusDictionary]
public class CorpusProperties
{
}

public static class CorpusExtensions
{
    public static string DefaultObjectPath { get; } = "/root/path";
    public static string[] KnownObjectPaths { get; } = new[] { "/root/path", "/root/path/inner" };

}