
using System.Collections.Immutable;
using System.Text;
using static Dbus.ContractGenerator.DbusGeneratorConstants;
using static Dbus.ContractGenerator.DbusGeneratorNaming;

namespace Dbus.ContractGenerator;

internal static class DbusSourceEmitter
{
    internal static string BuildSource(DbusInterfaceModel model, GeneratorConfiguration configuration)
    {
        var generatedNamespace = configuration.GeneratedNamespace;
        var qtTypeHintMappings = configuration.QtTypeHintMappings;
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable disable");
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using System.Threading.Tasks;");
        builder.AppendLine("using Dbus.Contracts;");
        builder.AppendLine();
        builder.Append("namespace ");
        builder.Append(generatedNamespace);
        builder.AppendLine(";");
        builder.AppendLine();
        WriteMemberStabilityAttributes(builder, model.Annotations, "interface");
        builder.Append("[DbusInterface(\"");
        builder.Append(model.InterfaceName);
        builder.AppendLine("\")]");
        builder.Append("public interface ");
        builder.Append(model.InterfaceTypeName);
        builder.AppendLine(" : IDbusObject");
        builder.AppendLine("{");

        var usedInterfaceMemberNames = new HashSet<string>(StringComparer.Ordinal);
        var getAsyncMethodName = MakeUniqueIdentifier("GetAsync", usedInterfaceMemberNames, "GetAsync");
        var getAllAsyncMethodName = MakeUniqueIdentifier("GetAllAsync", usedInterfaceMemberNames, "GetAllAsync");
        var setAsyncMethodName = MakeUniqueIdentifier("SetAsync", usedInterfaceMemberNames, "SetAsync");
        var watchPropertiesAsyncMethodName = MakeUniqueIdentifier("WatchPropertiesAsync", usedInterfaceMemberNames, "WatchPropertiesAsync");

        foreach (var method in model.Methods)
        {
            var methodName = MakeUniqueIdentifier(
                EnsureAsyncSuffix(BuildIdentifierSuffix(method.Name, "Method")),
                usedInterfaceMemberNames,
                "MethodAsync");
            WriteMemberStabilityAttributes(builder, method.Annotations, "method", "    ");
            builder.Append("    ");
            builder.Append(FormatMethodSignature(method, methodName, qtTypeHintMappings));
            builder.AppendLine(";");
        }

        foreach (var signal in model.Signals)
        {
            var signalWatcherName = MakeUniqueIdentifier(
                "Watch" + BuildIdentifierSuffix(signal.Name, "Signal") + "Async",
                usedInterfaceMemberNames,
                "WatchSignalAsync");
            WriteMemberStabilityAttributes(builder, signal.Annotations, "signal", "    ");
            builder.Append("    ");
            builder.Append(FormatSignalWatcherSignature(signal, signalWatcherName, qtTypeHintMappings));
            builder.AppendLine(";");
        }

        builder.Append("    Task<T> ");
        builder.Append(EscapeIdentifier(getAsyncMethodName));
        builder.AppendLine("<T>(string prop);");
        builder.Append("    Task<");
        builder.Append(model.PropertyTypeName);
        builder.Append("> ");
        builder.Append(EscapeIdentifier(getAllAsyncMethodName));
        builder.AppendLine("();");
        builder.Append("    Task ");
        builder.Append(EscapeIdentifier(setAsyncMethodName));
        builder.AppendLine("(string prop, object val);");
        builder.Append("    Task<IDisposable> ");
        builder.Append(EscapeIdentifier(watchPropertiesAsyncMethodName));
        builder.AppendLine("(Action<DbusPropertyChanges> handler);");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("[DbusDictionary]");
        builder.Append("public class ");
        builder.Append(model.PropertyTypeName);
        builder.AppendLine();
        builder.AppendLine("{");
        var usedPropertyNames = new HashSet<string>(StringComparer.Ordinal);
        foreach (var property in model.Properties)
        {
            var propertyIdentifier = MakeUniqueIdentifier(
                BuildIdentifierSuffix(property.Name, "Property"),
                usedPropertyNames,
                "Property");
            WriteMemberStabilityAttributes(builder, property.Annotations, "property", "    ");
            builder.Append("    public ");
            builder.Append(FormatType(property.Type, property.QtTypeHint, qtTypeHintMappings));
            builder.Append(' ');
            builder.Append(EscapeIdentifier(propertyIdentifier));
            builder.AppendLine(" { get; set; } = default!;");
        }

        builder.AppendLine("}");
        builder.AppendLine();
        builder.Append("public static class ");
        builder.Append(model.ExtensionTypeName);
        builder.AppendLine();
        builder.AppendLine("{");
        var defaultObjectPath = model.ObjectPaths.Length == 0 ? "/" : model.ObjectPaths[0];
        builder.Append("    public static string DefaultObjectPath { get; } = \"");
        builder.Append(defaultObjectPath);
        builder.AppendLine("\";");
        builder.Append("    public static string[] KnownObjectPaths { get; } = new[] { ");
        for (var pathIndex = 0; pathIndex < model.ObjectPaths.Length; pathIndex++)
        {
            if (pathIndex > 0)
            {
                builder.Append(", ");
            }

            builder.Append('"');
            builder.Append(model.ObjectPaths[pathIndex]);
            builder.Append('"');
        }

        builder.AppendLine(" };");
        builder.AppendLine();

        var usedExtensionMethodNames = new HashSet<string>(StringComparer.Ordinal);
        foreach (var property in model.Properties)
        {
            var propertySuffix = BuildIdentifierSuffix(property.Name, "Property");
            var getPropertyMethodName = MakeUniqueIdentifier(
                "Get" + propertySuffix + "Async",
                usedExtensionMethodNames,
                "GetPropertyAsync");
            var propertyType = FormatType(property.Type, property.QtTypeHint, qtTypeHintMappings);
            var canRead = !string.Equals(property.Access, "write", StringComparison.OrdinalIgnoreCase);
            var canWrite = string.Equals(property.Access, "write", StringComparison.OrdinalIgnoreCase) ||
                           string.Equals(property.Access, "readwrite", StringComparison.OrdinalIgnoreCase);

            if (canRead)
            {
                WriteMemberStabilityAttributes(builder, property.Annotations, "property", "    ");
                builder.Append("    public static Task<");
                builder.Append(propertyType);
                builder.Append("> ");
                builder.Append(EscapeIdentifier(getPropertyMethodName));
                builder.Append("(this ");
                builder.Append(model.InterfaceTypeName);
                builder.AppendLine(" o)");
                builder.AppendLine("    {");
                builder.AppendLine("        ArgumentNullException.ThrowIfNull(o);");
                builder.Append("        return o.");
                builder.Append(EscapeIdentifier(getAsyncMethodName));
                builder.Append("<");
                builder.Append(propertyType);
                builder.Append(">(\"");
                builder.Append(property.Name);
                builder.AppendLine("\");");
                builder.AppendLine("    }");
            }

            if (canWrite)
            {
                var setPropertyMethodName = MakeUniqueIdentifier(
                    "Set" + propertySuffix + "Async",
                    usedExtensionMethodNames,
                    "SetPropertyAsync");
                if (canRead)
                {
                    builder.AppendLine();
                }

                WriteMemberStabilityAttributes(builder, property.Annotations, "property", "    ");
                builder.Append("    public static Task ");
                builder.Append(EscapeIdentifier(setPropertyMethodName));
                builder.Append("(this ");
                builder.Append(model.InterfaceTypeName);
                builder.Append(" o, ");
                builder.Append(propertyType);
                builder.AppendLine(" val)");
                builder.AppendLine("    {");
                builder.AppendLine("        ArgumentNullException.ThrowIfNull(o);");
                builder.Append("        return o.");
                builder.Append(EscapeIdentifier(setAsyncMethodName));
                builder.Append("(\"");
                builder.Append(property.Name);
                builder.AppendLine("\", val);");
                builder.AppendLine("    }");
            }

            builder.AppendLine();
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void WriteMemberStabilityAttributes(
        StringBuilder builder,
        DbusAnnotationSet annotations,
        string memberKind,
        string indent = "")
    {
        if (annotations.IsEmpty)
        {
            return;
        }

        if (annotations.HasTrueFlag(
                DbusDeprecatedAnnotation,
                "org.freedesktop.DBus.Method.Deprecated",
                "org.freedesktop.DBus.Property.Deprecated",
                "org.freedesktop.DBus.Signal.Deprecated"))
        {
            builder.Append(indent);
            builder.Append("[Obsolete(\"D-Bus ");
            builder.Append(memberKind);
            builder.AppendLine(" is marked as deprecated.\")]");
        }
        else if (annotations.HasTrueFlag(
                     DbusExperimentalAnnotation,
                     "org.freedesktop.DBus.Method.Experimental",
                     "org.freedesktop.DBus.Property.Experimental",
                     "org.freedesktop.DBus.Signal.Experimental"))
        {
            builder.Append(indent);
            builder.Append("[Obsolete(\"D-Bus ");
            builder.Append(memberKind);
            builder.AppendLine(" is marked as experimental.\")]");
        }
    }

    private static string FormatMethodSignature(
        DbusMethodModel method,
        string methodName,
        ImmutableDictionary<string, string> qtTypeHintMappings)
    {
        var builder = new StringBuilder();
        var usedArgumentNames = new HashSet<string>(StringComparer.Ordinal);
        builder.Append(FormatMethodReturnType(method, qtTypeHintMappings));
        builder.Append(' ');
        builder.Append(EscapeIdentifier(methodName));
        builder.Append('(');

        for (var index = 0; index < method.InArguments.Length; index++)
        {
            if (index > 0)
            {
                builder.Append(", ");
            }

            var argument = method.InArguments[index];
            method.InQtTypeHints.TryGetValue(index, out var qtTypeHint);
            builder.Append(FormatType(argument.Type, qtTypeHint, qtTypeHintMappings));
            builder.Append(' ');
            var argumentName = MakeUniqueIdentifier(
                ToSafeIdentifier(argument.Name, $"arg{index}"),
                usedArgumentNames,
                $"arg{index}");
            builder.Append(EscapeIdentifier(argumentName));
        }

        builder.Append(')');
        return builder.ToString();
    }

    private static string FormatSignalWatcherSignature(
        DbusSignalModel signal,
        string methodName,
        ImmutableDictionary<string, string> qtTypeHintMappings)
    {
        var builder = new StringBuilder();
        builder.Append("Task<IDisposable> ");
        builder.Append(EscapeIdentifier(methodName));
        builder.Append('(');
        builder.Append(FormatSignalHandlerType(signal.Arguments, signal.QtTypeHints, qtTypeHintMappings));
        builder.Append(" handler, Action<Exception> onError = null)");
        return builder.ToString();
    }

    private static string FormatMethodReturnType(
        DbusMethodModel method,
        ImmutableDictionary<string, string> qtTypeHintMappings)
    {
        if (method.NoReply)
        {
            return "Task";
        }

        var outArguments = method.OutArguments;
        if (outArguments.IsDefaultOrEmpty)
        {
            return "Task";
        }

        if (outArguments.Length == 1)
        {
            method.OutQtTypeHints.TryGetValue(0, out var qtTypeHint);
            return $"Task<{FormatType(outArguments[0].Type, qtTypeHint, qtTypeHintMappings)}>";
        }

        return $"Task<{FormatTupleType(outArguments, method.OutQtTypeHints, qtTypeHintMappings)}>";
    }

    private static string FormatSignalHandlerType(
        ImmutableArray<DbusArgumentModel> arguments,
        ImmutableDictionary<int, string> qtTypeHints,
        ImmutableDictionary<string, string> qtTypeHintMappings)
    {
        if (arguments.IsDefaultOrEmpty)
        {
            return "Action";
        }

        if (arguments.Length == 1)
        {
            qtTypeHints.TryGetValue(0, out var qtTypeHint);
            return $"Action<{FormatType(arguments[0].Type, qtTypeHint, qtTypeHintMappings)}>";
        }

        return $"Action<{FormatTupleType(arguments, qtTypeHints, qtTypeHintMappings)}>";
    }

    private static string FormatTupleType(
        ImmutableArray<DbusArgumentModel> arguments,
        ImmutableDictionary<int, string> qtTypeHints,
        ImmutableDictionary<string, string> qtTypeHintMappings)
    {
        var builder = new StringBuilder();
        var usedTupleNames = new HashSet<string>(StringComparer.Ordinal);
        builder.Append('(');

        for (var index = 0; index < arguments.Length; index++)
        {
            if (index > 0)
            {
                builder.Append(", ");
            }

            var argument = arguments[index];
            qtTypeHints.TryGetValue(index, out var qtTypeHint);
            builder.Append(FormatType(argument.Type, qtTypeHint, qtTypeHintMappings));
            builder.Append(' ');
            var tupleElementName = MakeUniqueIdentifier(
                ToCamelCaseIdentifier(argument.Name, $"item{index + 1}"),
                usedTupleNames,
                $"item{index + 1}");
            builder.Append(EscapeIdentifier(tupleElementName));
        }

        builder.Append(')');
        return builder.ToString();
    }

    private static string FormatType(
        DbusType type,
        string? qtTypeHint,
        ImmutableDictionary<string, string> qtTypeHintMappings)
    {
        if (TryMapQtTypeHintToClrType(qtTypeHint, qtTypeHintMappings, out var mappedQtType))
        {
            return mappedQtType;
        }

        switch (type)
        {
            case PrimitiveDbusType primitiveType:
                return primitiveType.Code switch
                {
                    'y' => "byte",
                    'b' => "bool",
                    'n' => "short",
                    'q' => "ushort",
                    'i' => "int",
                    'u' => "uint",
                    'x' => "long",
                    't' => "ulong",
                    'd' => "double",
                    's' => "string",
                    'o' => "DbusObjectPath",
                    'g' => "string",
                    'h' => "CloseSafeHandle",
                    'v' => "object",
                    _ => throw new DbusSignatureParseException(primitiveType.Code.ToString(), $"Unsupported primitive D-Bus signature '{primitiveType.Code}'.")
                };

            case ArrayDbusType arrayType:
                return $"{FormatType(arrayType.ElementType, null, qtTypeHintMappings)}[]";

            case DictDbusType dictType:
                return $"IDictionary<{FormatType(dictType.KeyType, null, qtTypeHintMappings)}, {FormatType(dictType.ValueType, null, qtTypeHintMappings)}>";

            case StructDbusType structType:
            {
                if (structType.Elements.Length == 0)
                {
                    return "System.ValueTuple";
                }

                if (structType.Elements.Length == 1)
                {
                    return $"System.ValueTuple<{FormatType(structType.Elements[0], null, qtTypeHintMappings)}>";
                }

                var builder = new StringBuilder();
                builder.Append('(');
                for (var index = 0; index < structType.Elements.Length; index++)
                {
                    if (index > 0)
                    {
                        builder.Append(", ");
                    }

                    builder.Append(FormatType(structType.Elements[index], null, qtTypeHintMappings));
                }

                builder.Append(')');
                return builder.ToString();
            }

            default:
                throw new InvalidOperationException("Unexpected D-Bus type model.");
        }
    }

    private static bool TryMapQtTypeHintToClrType(
        string? qtTypeHint,
        ImmutableDictionary<string, string> qtTypeHintMappings,
        out string clrType)
    {
        return DbusQtTypeHintResolver.TryResolveClrType(qtTypeHint, qtTypeHintMappings, out clrType);
    }
}
