// <auto-generated/>
#nullable disable
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Dbus.Contracts;

namespace GeneratorHarness.Generated;

[DbusInterface("org.example.Annotated")]
[DbusProperties(typeof(DbIAnnotatedContractProperties))]
public interface DbIAnnotatedContract : IDbusObject
{
    [Obsolete("D-Bus method is marked as deprecated.")]
    [DbusMethod("Execute", "u", "", true)]
    Task ExecuteAsync(ulong target);
    Task<T> GetAsync<T>(string prop);
    Task<DbIAnnotatedContractProperties> GetAllAsync();
    Task SetAsync(string prop, object val);
    Task<IDisposable> WatchPropertiesAsync(Action<DbusPropertyChanges> handler);
}

[DbusDictionary]
public class DbIAnnotatedContractProperties
{
    [DbusProperty("Items", "as")]
    public string[] Items { get; set; } = default!;
}

public static class DbIAnnotatedContractExtensions
{
    public static string DefaultObjectPath { get; } = "/";
    public static string[] KnownObjectPaths { get; } = new[] { "/" };

    public static Task<string[]> GetItemsAsync(this DbIAnnotatedContract o)
    {
        ArgumentNullException.ThrowIfNull(o);
        return o.GetAsync<string[]>("Items");
    }

}